version: '3.8'

services:
  url_shortener_test_postgres: # Needs updating
    image: postgres:alpine
    container_name: url_shortener_test_postgres # Needs updating
    restart: 'no'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER']
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env.test
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5444:5432'
    volumes:
      - url_shortener_test_postgres_data:/var/lib/postgresql/data # Needs updating

  url_shortener_test_redis: # Needs updating
    image: redis:alpine
    container_name: url_shortener_test_redis # Needs updating
    ports:
      - '6380:6379'
    volumes:
      - url_shortener_test_redis_data:/data # Needs updating

networks:
  default:
    name: url_shortener_test # Needs updating

volumes:
  url_shortener_test_postgres_data: # Needs updating
  url_shortener_test_redis_data: # Needs updating
